### PR TITLE
doc: add example directory

### PR DESCRIPTION
**Pull request by Bogdanp**
This makes getting started with local builds easier by automating most
of the VM creation process.

### CODE REVIEW

**Comment by samth** [comment]
This is great. I do wonder if there's some way to avoid both using Vagrant and using the re-implementation of part of Vagrant that is the `remote-shell` package, but that's probably a subject for another day.

**Comment by Bogdanp** [comment]
> I do wonder if there's some way to avoid both using Vagrant and using the re-implementation of part of Vagrant that is the remote-shell package, but that's probably a subject for another day.

I've thought about going that route, but figured it would be too much work for one PR. If I can find the time next week, I'll take a look at adding support for the Vagrant box format to `remote-shell`. That should then make it easy to use that package to create VMs and we could drop the Vagrant dependency from here.

>  Bogdanp force-pushed the Bogdanp:master branch from f4b140d to 32c7291 8 minutes ago

I initially forgot to push a change I had made to disable outgoing connections within the VMs so that's what this is about.

**Comment by samth** [comment]
This looks good to me. @mflatt is this good to merge?

**Comment by samth** [comment]
@Bogdanp sorry for not getting this merged earlier. Can you resolve the readme conflicts?

**Comment by Bogdanp** [comment]
@samth no worries! I can do that tomorrow morning.

**Comment by Bogdanp** [comment]
@samth I've merged the two READMEs

**Pull request merged**
